#!/bin/bash

if [[! -d airootfs/root ]]
then
	echo "creating root dir"
	mkdir airootfs/root
	echo "created root dir"
fi

if [[ -d airootfs/root/indigo-installer ]]
then
	echo "removing previous installer..."
	rm -r airootfs/root/indigo-installer
	echo "previous installer removed"
fi


echo "cloning installer..."
git clone https://github.com/megabyte112/indigo-installer.git airootfs/root/indigo-installer
echo "finished cloning installer"


echo "checking for existing working directory..."
if [[ -d /tmp/indiso ]]
then
	echo "removing existing working directory..."
	sudo rm -r /tmp/indiso
	echo "done"
fi


echo "building iso..."

sudo mkarchiso -v -w /tmp/indiso .

echo "build complete."
