#!/bin/bash

WORK_DIR=/tmp/indiso-build


echo "[mkindiso] mkindiso, by the indigo team"

echo ""

echo "[mkindiso] mkindiso working directory:" $WORK_DIR

echo ""

# check if root
if [ "$(whoami)" == "root" ]; then
	echo "[mkindiso] do not run this script as root!"
	exit 1
fi

# check if archiso is installed
if ! command -v mkarchiso &> /dev/null
then
	echo "[mkindiso] archiso is not installed"
	echo "[mkindiso] install archiso and try again"
	exit 1
fi

# check if sudo is installed
if ! command -v sudo &> /dev/null
then
	echo "[mkindiso] sudo is not installed"
	echo "[mkindiso] install sudo and try again"
	exit 1
fi

# check if the user has notify-send, do as user
if command -v notify-send &> /dev/null
then
	notify=1
else
	echo "[mkindiso] notify-send not found, disabling notifications"
	notify=0
fi

echo ""
echo "[mkindiso] okay, let's do this!!"
echo "[mkindiso] prepare yourself - and enjoy the wait."

# notify user as $USER
if [ $notify == 1 ]; then
	notify-send "mkindiso" "building iso..."
fi

echo ""
echo "[mkindiso] building iso..."
echo ""
echo "[mkindiso] can has sudo??"
sudo mkarchiso -v -w $WORK_DIR . && complete=1 || complete=0

if [ $complete == 1 ]; then
	iso=$(ls out/indigo-*.iso | tail -n 1)
	iso=${iso:4}
	echo $(sha512sum out/$iso) > out/$iso.sha512sum
	echo "[mkindiso] build complete :D"
	if [ $notify == 1 ]; then
		notify-send "mkindiso" "build complete :D"
	fi
else
	echo ""
	echo "[mkindiso] build failed :("
	if [ $notify == 1 ]; then
		notify-send "mkindiso" "build failed :("
	fi
	exit 1
fi

echo ""

# ask to delete working directory
echo "[mkindiso] remove working directory? [Y/n]: "
echo -n "[mkindiso] > "
read delete

if [[ ("$delete" != "") && ("$delete" != "Y") && ("$delete" != "y") ]]; then
	echo "[mkindiso] not deleting working directory"
else
	echo "[mkindiso] cleaning up working directory (at $WORK_DIR)..."
	echo ""
	echo "[mkindiso] can has sudo one more time??"
	sudo rm -rf $WORK_DIR
	echo "[mkindiso] removed working directory"
fi

echo ""
echo "[mkindiso] done!"
echo "[mkindiso] check the 'out' folder for your iso file."
exit 0
