#!/bin/bash

WORK_DIR=/tmp/indiso-build
INSTALLER_FINAL_DIR=airootfs/etc/indigo-installer


echo "[mkindiso] mkindiso, by the indigo team"

echo ""

echo "[mkindiso] installer directory:" $INSTALLER_FINAL_DIR
echo "[mkindiso] working directory:" $WORK_DIR

echo ""

sleep 1

echo "[mkindiso] can has sudo??"

sudo echo "[mkindiso] thank you <3"

echo ""

echo "[mkindiso] checking for existing install script..."
sleep 0.5
if [[ -d $INSTALLER_FINAL_DIR ]]
then
	echo "[mkindiso] removing previous install script..."
	sleep 0.5
	rm -rf $INSTALLER_FINAL_DIR
	echo "[mkindiso] removed install script"
fi

echo ""

echo "[mkindiso] cloning installer..."
sleep 1
echo ""
git clone https://github.com/megabyte112/indigo-installer.git $INSTALLER_FINAL_DIR
echo ""
echo "[mkindiso] finished cloning installer"

echo ""

echo "[mkindiso] checking for existing working directory..."
sleep 0.5
if [[ -d $WORK_DIR ]]
then
	echo "[mkindiso] removing existing working directory..."
	sleep 0.5
	sudo rm -r $WORK_DIR
	echo "[mkindiso] removed working directory"
fi

echo ""

sleep 0.5

echo "[mkindiso] okay, let's do this!!"
echo "[mkindiso] prepare yourself - and enjoy the wait."

echo ""

echo "[mkindiso] building iso..."

sleep 3

sudo mkarchiso -v -w $WORK_DIR . && echo -e "\n[mkindiso] build complete :D\n[mkindiso] check the 'out' folder for your iso." || echo -e "\n[mkindiso] build failed :("

echo ""
echo "[mkindiso] cleaning up working directory (at $WORK_DIR)..."
sudo rm -rf $WORK_DIR
echo "[mkindiso] done!"

