import:
  - ~/.config/alacritty/alacritty-catppuccin-mocha.yml

window:
  opacity: 0.9

font:
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  bold_italic:
    family: Fira Code
    style: Bold Italic

  size: 12
