#! /bin/sh

# hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

# monitors
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	8
bspc config window_gap           	8

bspc config split_ratio          	0.50
bspc config single_monocle       	true
bspc config focus_follows_pointer	true
bspc config borderless_monocle   	false
bspc config gapless_monocle      	true

bspc config focused_border_color	"#1e1e2e"
bspc config normal_border_color		"#181825"
bspc config active_border_color		"#1e1e2e"
bspc config presel_feedback_color	"#313244"
bspc config presel_border_color		"#313244"

bspc config pointer_modifier     	Mod4

bash $HOME/firstboot.sh &
xset r rate 200 50 &
picom -fb &
$HOME/.fehbg &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh --shapes &
dunst &
conky -c $HOME/.config/conky/mocha.conf &
betterlockscreen -l dim