#!/bin/bash

echo "Installer isn't ready yet - you'll have to install manually :("
echo "if you really wanna risk damaging your PC, venture forth within this script, and uncomment the python call."

# python /etc/indigo-installer/indigoinstaller.py
